# Generated by Django 4.1.7 on 2023-03-31 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metr', '0004_loservalue_owner_task_owner_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loservalue',
            name='lastUpdated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
