# Generated by Django 4.1.7 on 2023-03-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metr', '0002_loservalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='loservalue',
            name='updatesCount',
            field=models.IntegerField(default=0),
        ),
    ]
