# Generated by Django 4.1.7 on 2023-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metr', '0003_loservalue_updatescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loservalue',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
