# Generated by Django 4.1.7 on 2023-04-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metr', '0005_loservalue_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
