# Generated by Django 4.1.7 on 2023-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metr', '0007_loservalue_lastfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loservalue',
            name='lastUpdated',
        ),
        migrations.AlterField(
            model_name='loservalue',
            name='lastFill',
            field=models.BooleanField(default=True),
        ),
    ]
